import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Intro from "@/components/intro/intro";
import QuickAccess from "@/components/quickAccess/QuickAccess";
import News from "@/components/news/News";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Gelir İdaresi Başkanlığı</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Afacad:ital,wght@0,400..700;1,400..700&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&family=Waterfall&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Ephesis&family=Nunito:ital,wght@0,200..1000;1,200..1000&family=Waterfall&display=swap" rel="stylesheet"></link>
      </Head>
          <div
          >
            <main className={styles.main}>
              <Intro />
              <News />
              <QuickAccess />
            </main>
          </div>
        </>
        );
}
